### ISSUE TITLE
great script, minor issue

### ISSUE THREAD

**Issue by JLT032** [eelcohn/WebsiteSecurityAssessment#1]
Thank for this great script, well written, easy to review.

However for lines 239 and 240 there are invisible characters in there which make for a parse error on the " quotes which are not written like that in the code on a different machine.

**Comment by eelcohn** [comment]
Thanks, great to hear that you like the script!
Aparently the web-editor and/or my browser replaces the ASCII character " with an Unicode variant.
I've fixed this and it should work correctly now.
Please let me know what you think of the new layout of the output file.

**Comment by eelcohn** [comment]
This issue should be fixed by now.
